services:
  plex-hide-spoilers-docker:
    build: .
    container_name: plex-hide-spoilers-docker
    restart: unless-stopped
    ports:
      - "5845:5845"
    environment:
      - PLEX_URL=http://192.168.0.14:32400
      - PLEX_TOKEN=your-token-here
      - PLEX_LIBRARIES=['TV Shows']
      - SCAN_ON_STARTUP=true
